nitkmarket/market/urls.py
from django.urls import path

from . import views
from django.conf.urls import url

app_name = 'market'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('myprofile/myadds', views.myadds, name='myadds'),
    path('updateprofile/', views.update_profile, name='update_profile'),
    path('post/', views.add, name='add'),
    path('home/', views.market, name='market'),
    path('sell/', views.sell, name='sell'),
    path('rent/', views.rent, name='rent'),
    path('search/<slug:keyword>/', views.search, name='search'),
    url(r'^show_add/(\d+)/$', views.show_add, name="show_add"),
    url(r'^edit_add/(\d+)/$', views.edit_add, name="edit_add"),
]

nitkmarket/nitkmarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('market.urls')),
    path('profile/', include('market.urls')),
    path('add/', include('market.urls')),
    path('market/', include('market.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

nitkmarket/market/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField(max_length=5000, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    mobile=models.IntegerField(default=888888888,blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class item(models.Model):
    user_id=models.IntegerField(blank=True,null=True)
    price=models.CharField(max_length=100,blank=True)
    description=models.TextField(max_length=5000,blank=True)
    date = models.DateTimeField(auto_now_add=True,null=True)
    type=models.CharField(max_length=10,blank=True)
    tag=models.CharField(max_length=1000,blank=True)
    title=models.CharField(max_length=1000,blank=True)
    imagefile= models.FileField(upload_to='images/', null=True, verbose_name="")
    status=models.TextField(max_length=50,default="notsold")

nitkmarket/market/forms.py
from django.forms import ModelForm
from market.models import Profile,item
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from django.db import models


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('address','birth_date','mobile')

class ImageForm(forms.ModelForm):
    class Meta:
        model= item
        labels = {
        "title": "Title of advertisement ",
        "description":"Description of your product",
        "price":"Maximum asking price       ",
        "imagefile":"Upload an image of your product",
        "type":"Rent or Sell??        ",
        "tag":"Some keywords associated with the product",
    }
        fields= ('title','description','price','imagefile','type','tag' )

class query(forms.Form):
    keyword=forms.CharField(max_length=100)

nitkmarket/market/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render,redirect
from .forms import UserForm,ProfileForm,ImageForm,query
from .models import Profile,item
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def myprofile(request):
    if request.user.is_authenticated:
        username=request.user.username
        date_c=request.user.date_joined
        return render(request, 'myprofile.html', {'username':username,'date_c':date_c,})
    else:
        error="not signed in"
        return render(request, 'myprofile.html', {'error':error,})

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect('market:myprofile')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'updateprofile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def add(request):
    form= ImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        q=item.objects.last()
        add_id=q.id
        q.user_id=request.user.id
        q.save()
        return HttpResponseRedirect(reverse('market:show_add', args=(add_id,)))


    context= {'form': form,}


    return render(request, 'add.html', context)

def show_add(request,add_id):
    q=get_object_or_404(item, id=add_id)
    imagefile= q.imagefile
    description=q.description
    title=q.title
    price=q.price
    type=q.type
    date=q.date
    user_id=q.user_id
    status=0
    if q.status=="sold":
        status=1
    w=get_object_or_404(User,id=user_id)
    username=w.username
    address=w.profile.address
    mobile=w.profile.mobile
    email=w.email
    context={'imagefile':imagefile,'description':description,'title':title,'type':type,'price':price,'time':date,'user_id':user_id,'username':username,'email':email,'address':address,'add_id':add_id,'status':status,'mobile':mobile,}
    return render(request, 'show_add.html', context)

def market(request):
    form=query()
    if request.POST:
        form=query(request.POST)
        if form.is_valid():
            w=form.cleaned_data['keyword']
            return HttpResponseRedirect(reverse('market:search', args=(w,)))

    titles=item.objects.filter(type="Sell",status="notsold").exclude(user_id=request.user.id).values_list('title',flat=True).order_by('-date')[0:4]
    prices=item.objects.filter(type="Sell",status="notsold").exclude(user_id=request.user.id).values_list('price',flat=True).order_by('-date')[0:4]
    ids=item.objects.filter(type="Sell",status="notsold").exclude(user_id=request.user.id).values_list('id',flat=True).order_by('-date')[0:4]
    imagefile=item.objects.filter(type="Sell",status="notsold").exclude(user_id=request.user.id).values_list('imagefile',flat=True).order_by('-date')[0:4]
    s_id=[]
    usernames=[]
    for i in range(len(ids)):
        q=get_object_or_404(item, id=ids[i])
        s_id.append(q.user_id)
    for i in range(len(ids)):
        q=get_object_or_404(User, id=s_id[i])
        usernames.append(q.username)

    titlesr=item.objects.filter(type="Rent",status="notsold").exclude(user_id=request.user.id).values_list('title',flat=True).order_by('-date')[0:4]
    pricesr=item.objects.filter(type="Rent",status="notsold").exclude(user_id=request.user.id).values_list('price',flat=True).order_by('-date')[0:4]
    idsr=item.objects.filter(type="Rent",status="notsold").exclude(user_id=request.user.id).values_list('id',flat=True).order_by('-date')[0:4]
    imagefiler=item.objects.filter(type="Rent",status="notsold").exclude(user_id=request.user.id).values_list('imagefile',flat=True).order_by('-date')[0:4]
    s_idr=[]
    usernamesr=[]
    for i in range(len(idsr)):
        q=get_object_or_404(item, id=idsr[i])
        s_idr.append(q.user_id)
    for i in range(len(idsr)):
        q=get_object_or_404(User, id=s_idr[i])
        usernamesr.append(q.username)
    context={'latest_s':titles,'list1':usernames,'list2':prices,'id':ids,'imagefile':imagefile,'latest_r':titlesr,'list1r':usernamesr,'list2r':pricesr,'idr':idsr,'imagefiler':imagefiler ,'form':form,}
    return render(request, 'market.html', context)

def sell(request):
    objects=item.objects.filter(type="Sell",status="notsold").exclude(user_id=request.user.id).order_by('-date')

    context={'objects':objects,}
    return render(request,'sell.html',context)

def rent(request):
    objects=item.objects.filter(type="Rent",status="notsold").exclude(user_id=request.user.id).order_by('-date')
    context={'objects':objects,}
    return render(request,'rent.html',context)
def search(request,keyword):
    objects=item.objects.filter(tag__icontains=keyword,status="notsold").exclude(user_id=request.user.id).order_by('-date')
    context={'objects':objects,'keyword':keyword,}
    return render(request,'search.html',context)
def myadds(request):
    if request.user.is_authenticated:
        username_id=request.user.id
        objects=item.objects.filter(user_id=username_id).order_by('-date')
        return render(request, 'myadds.html', {'objects':objects,})
    else:
        error="not signed in"
        return render(request, 'myadds.html', {'error':error,})
def edit_add(request,add_id):
    q=get_object_or_404(item,id=add_id)
    q.status="sold"
    q.save()
    return HttpResponseRedirect(reverse('market:show_add', args=(add_id,)))

nitkmarket/market/templates/market.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Nitk market</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />



	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'market/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'market/css/icomoon.css' %}">
	<!-- Themify Icons-->
	<link rel="stylesheet" href="{% static 'market/css/themify-icons.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'market/css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'market/css/magnific-popup.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'market/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'market/css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'market/css/style.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<!-- Modernizr JS -->
	<script src="{% static 'market/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>

	<div class="gtco-loader"></div>

	<div id="page">


	<div class="page-inner">
	<nav class="gtco-nav" role="navigation" style="background-color:black">
		<div class="gtco-container">

			<div class="row">
				<div class="col-sm-4 col-xs-12">
					<div id="gtco-logo"><a href="/">Nitk market <em>.</em></a></div>
				</div>
				<div class="col-xs-8 text-right menu-1">
					<ul>
            {% if user.is_authenticated %}
            <li><b style="color:magenta">  Hi {{ user.username }}!</b></li>
            <li><a href="/market/home"><b style="color:magenta">Explore products</b></a></li>
              <li>
              <a href="/profile/myprofile"><b style="color:magenta">My Profile</b></a></li>
                  <li><a href="/profile/myprofile/myadds"><b style="color:magenta">My Adds</b></a></li>
							<li>
              <a href="/add/post"><b style="color:magenta">Post an ADD</b></a></li>
							<li>
              <a href="{% url 'logout' %}"><b style="color:magenta">LOG OUT</b></a></li>
              <li>
                {% else %}<li><a href="/market/home"><b style="color:magenta">Explore products</b></a></li><li>
                  <a href="{% url 'login' %}"><b style="color:magenta">LOGIN</b></a></li>
                  <li><a href="/accounts/signup"><b style="color:magenta">SIGN UP</b></a></li>
                {% endif %}
						<li><a href="https://github.com/harshnitk17/web-club-recruitment-pastebin/blob/master/README.md" target="_blank"><b>FAQ</b></a></li>



					</ul>
				</div>
			</div>

		</div>
	</nav>


  <div id="gtco-subscribe">
  		<div class="gtco-container">
  			<div class="row animate-box">
  				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
  					<h2>Search a product</h2>
  					<p>By keyword</p>
  				</div>
  			</div>
  			<div class="row animate-box">
  				<div class="col-md-8 col-md-offset-2">
  					<form class="form-inline" method="POST">
              {% csrf_token %}
  						<div class="col-md-6 col-sm-6">
  							<div class="form-group">
  								<label for="id_keyword" class="sr-only" >Enter keyword</label>
  								<input type="text" class="form-control" id="id_keyword" placeholder="Enter a keyword" name="keyword">
  							</div>
  						</div>
  						<div class="col-md-6 col-sm-6">
  							<button type="submit" class="btn btn-default btn-block">Search</button>
  						</div>
  					</form>
  				</div>
  			</div>
  		</div>
  	</div>

		<div class="gtco-section border-bottom">
			<div class="gtco-container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
						<h2>Products on Sale</h2>
						<p>Newest 4 products (sorted by date)</p>
					</div>
				</div>


				<div class="row">
			{% for names in latest_s %}
				<div class="col-md-3">
					<div class="price-box">
						<h2 class="pricing-plan">{{ names }}</h2>
						{% if forloop.counter is 1 %}
						<h3>Seller:{{list1.0}}</h3>
						<h3>Price:{{list2.0}}</h3>
						<p><center><img src='{{ MEDIA_URL }}{{ imagefile.0 }}' class="center" alt="product photo" width="80px" height="80px"
					<button>	<a href="{% url 'market:show_add' id.0 %}" target="_blank" class="btn btn-default btn-sm">Open add</a></button>{% endif %}
						{% if forloop.counter is 2 %}
						<h3>Seller:{{list1.1}}</h3>
						<h3>Price:{{list2.1}}</h3>
						<p><center><img src='{{ MEDIA_URL }}{{ imagefile.1 }}' class="center" alt="product photo" width="80px" height="80px"
					<button>	<a href="{% url 'market:show_add' id.1 %}" target="_blank" class="btn btn-default btn-sm">Open add</a></button>{% endif %}
						{% if forloop.counter is 3 %}
						<h3>Seller:{{list1.2}}</h3>
						<h3>Price:{{list2.2}}</h3>
						<p><center><img src='{{ MEDIA_URL }}{{ imagefile.2 }}' class="center" alt="product photo" width="80px" height="80px"
						<button><a href="{% url 'market:show_add' id.2 %}" target="_blank" class="btn btn-default btn-sm">Open add</a></button>{% endif %}
						{% if forloop.counter is 4 %}
						<h3>Seller:{{list1.3}}</h3>
						<h3>Price:{{list2.3}}</h3>
						<p><center><img src='{{ MEDIA_URL }}{{ imagefile.3 }}' class="center" alt="product photo" width="80px" height="80px"
						<button><a href="{% url 'market:show_add' id.3 %}" target="_blank" class="btn btn-default btn-sm">Open add</a></button>{% endif %}


					</div>
				</div>{% endfor %}

			</div>
      <div class="row">
      <a href="/market/sell">  <button  class="btn btn-default btn-block">See all products on sale</button></a></div>
			</div>
		</div>

    <div class="gtco-section border-bottom">
      <div class="gtco-container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2 text-center gtco-heading">
            <h2>Products on Rent</h2>
            <p>Newest 4 products (sorted by date)</p>
          </div>
        </div>


        <div class="row">
      {% for names in latest_r %}
        <div class="col-md-3">
          <div class="price-box">
            <h2 class="pricing-plan">{{ namesr }}</h2>
            {% if forloop.counter is 1 %}
            <h3>Seller:{{list1r.0}}</h3>
            <h3>Price:{{list2r.0}}</h3>
            <p><center><img src='{{ MEDIA_URL }}{{ imagefiler.0 }}' class="center" alt="product photo" width="80px" height="80px"
          <button>	<a href="{% url 'market:show_add' idr.0 %}" target="_blank" class="btn btn-default btn-sm">Open add</a></button>{% endif %}
            {% if forloop.counter is 2 %}
            <h3>Seller:{{list1r.1}}</h3>
            <h3>Price:{{list2r.1}}</h3>
            <p><center><img src='{{ MEDIA_URL }}{{ imagefiler.1 }}' class="center" alt="product photo" width="80px" height="80px"
          <button>	<a href="{% url 'market:show_add' idr.1 %}" target="_blank" class="btn btn-default btn-sm">Open add</a></button>{% endif %}
            {% if forloop.counter is 3 %}
            <h3>Seller:{{list1r.2}}</h3>
            <h3>Price:{{list2r.2}}</h3>
            <p><center><img src='{{ MEDIA_URL }}{{ imagefiler.2 }}' class="center" alt="product photo" width="80px" height="80px"
            <button><a href="{% url 'market:show_add' idr.2 %}" target="_blank" class="btn btn-default btn-sm">Open add</a></button>{% endif %}
            {% if forloop.counter is 4 %}
            <h3>Seller:{{list1r.3}}</h3>
            <h3>Price:{{list2r.3}}</h3>
            <p><center><img src='{{ MEDIA_URL }}{{ imagefiler.3 }}' class="center" alt="product photo" width="80px" height="80px"
            <button><a href="{% url 'market:show_add' idr.3 %}" target="_blank" class="btn btn-default btn-sm">Open add</a></button>{% endif %}


          </div>
        </div>{% endfor %}

      </div>
      <div class="row">
        <a href="/market/rent"><button  class="btn btn-default btn-block">See all products on rent</button></a></div>
      </div>
    </div>


	<footer id="gtco-footer" role="contentinfo">
		<div class="gtco-container">
			<div class="row row-p	b-md">

				<div class="col-md-4">
					<div class="gtco-widget">
						<h3>About <span class="footer-logo">Nitk market<span>.<span></span></h3>
						<p>A website where students can buy or rent their stuff!!!</p>
					</div>
				</div>

				<div class="col-md-4 col-md-push-1">

				</div>

				<div class="col-md-4">
					<div class="gtco-widget">
						<h3>Get In Touch</h3>
						<ul class="gtco-quick-contact">
							<li><a href="#"><i class="icon-phone"></i> +91 My phone number</a></li>
							<li><a href="#"><i class="icon-mail2"></i> harshprakashgupta@gmail.com</a></li>

						</ul>
					</div>
				</div>

			</div>

			<div class="row copyright">
				<div class="col-md-12">
					<p class="pull-left">
						<small class="block">&copy; 2019  All Rights Reserved.</small>
						<small class="block">Designed by <a href="http://harshnitk17.github.io" target="_blank">Harsh Prakash Gupta</a> </small>
					</p>
					<p class="pull-right">
						<ul class="gtco-social-icons pull-right">

							<li><a href="https://www.linkedin.com/in/harsh-prakash-gupta-b9140816a/" target="_blank"><i class="icon-linkedin"></i></a></li>
							<li><a href="https://www.facebook.com/harshprakash.gupta" target="_blank"><i class="icon-facebook"></i></a></li>
							<li><a href="https://github.com/harshnitk17" target="_blank"><i style="font-size:24px" class="fa">&#xf09b;</i></a></li>

						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>
	</div>

	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>

	<!-- jQuery -->
	<script src="{% static 'market/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'market/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'market/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'market/js/jquery.waypoints.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'market/js/owl.carousel.min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'market/js/jquery.countTo.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'market/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'market/js/magnific-popup-options.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'market/js/main.js' %}"></script>

	</body>
</html>